# Generated by Django 6.0.1 on 2026-01-19 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(help_text='Numéro IMEI du device (15 chiffres)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="L'IMEI doit contenir exactement 15 chiffres", regex='^\\d{15}$')])),
                ('name', models.CharField(help_text='Nom personnalisé du device', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle_plate', models.CharField(blank=True, help_text="Plaque d'immatriculation", max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, help_text='Type de véhicule (voiture, moto, camion, etc.)', max_length=50, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('maintenance', 'En maintenance'), ('lost', 'Perdu'), ('deactivated', 'Désactivé')], default='active', max_length=20)),
                ('icon', models.CharField(default='car', help_text='Icône à afficher sur la carte', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Couleur en hexadécimal', max_length=7)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('last_position', models.JSONField(blank=True, default=dict, help_text='Dernière position connue (lat, lng, etc.)')),
                ('is_online', models.BooleanField(default=False)),
                ('update_interval', models.IntegerField(default=60, help_text='Intervalle de mise à jour en secondes')),
                ('speed_limit', models.IntegerField(default=0, help_text='Limite de vitesse pour les alertes (km/h)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('locate', 'Localisation'), ('reboot', 'Redémarrage'), ('set_interval', 'Définir intervalle'), ('set_apn', 'Configurer APN'), ('engine_stop', 'Arrêt moteur'), ('engine_resume', 'Reprise moteur'), ('custom', 'Personnalisée')], max_length=50)),
                ('command_data', models.JSONField(default=dict, help_text='Paramètres de la commande')),
                ('raw_command', models.TextField(blank=True, help_text='Commande brute envoyée au device', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('delivered', 'Délivrée'), ('executed', 'Exécutée'), ('failed', 'Échouée'), ('timeout', 'Expirée')], default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration de la commande", null=True)),
            ],
            options={
                'verbose_name': 'Commande device',
                'verbose_name_plural': 'Commandes devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('GT06', 'GT06'), ('GT06N', 'GT06N'), ('TK102', 'TK102'), ('TK103', 'TK103'), ('303', '303'), ('FMXXXX', 'FMXXXX (Teltonika)')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='device_models/')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Caractéristiques techniques du modèle')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de device',
                'verbose_name_plural': 'Modèles de devices',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='devices.device')),
                ('apn', models.CharField(blank=True, max_length=100, null=True)),
                ('apn_user', models.CharField(blank=True, max_length=100, null=True)),
                ('apn_password', models.CharField(blank=True, max_length=100, null=True)),
                ('authorized_numbers', models.JSONField(blank=True, default=list, help_text='Liste des numéros autorisés à envoyer des SMS au device')),
                ('reporting_interval_moving', models.IntegerField(default=60, help_text='Intervalle en mouvement (secondes)')),
                ('reporting_interval_stopped', models.IntegerField(default=300, help_text="Intervalle à l'arrêt (secondes)")),
                ('fuel_sensor_enabled', models.BooleanField(default=False)),
                ('temperature_sensor_enabled', models.BooleanField(default=False)),
                ('door_sensor_enabled', models.BooleanField(default=False)),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Paramètres personnalisés spécifiques au modèle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres device',
                'verbose_name_plural': 'Paramètres devices',
            },
        ),
    ]
