# Generated by Django 6.0.1 on 2026-01-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='devices', to='fleet.devicegroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicemodel'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status'], name='devices_dev_device__0a9c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['created_at'], name='devices_dev_created_e6fdd2_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['owner', 'status'], name='devices_dev_owner_i_d9e88d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['imei'], name='devices_dev_imei_94ab30_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_online'], name='devices_dev_is_onli_19f849_idx'),
        ),
    ]
