# Generated by Django 6.0.1 on 2026-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='analog_inputs',
            field=models.IntegerField(default=0, help_text="Nombre d'entrées analogiques"),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='digital_inputs',
            field=models.IntegerField(default=0, help_text="Nombre d'entrées numériques"),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='digital_outputs',
            field=models.IntegerField(default=0, help_text='Nombre de sorties numériques'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='has_canbus',
            field=models.BooleanField(default=False, help_text='Support CANBUS'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='supported_sensors',
            field=models.JSONField(blank=True, default=list, help_text="Liste des capteurs supportés (ex: ['fuel', 'temp', 'door'])"),
        ),
    ]
