# Generated by Django 6.0.1 on 2026-01-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_devicetariffplan'),
        ('devices', '0003_devicemodel_analog_inputs_devicemodel_digital_inputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='device_plan',
            field=models.ForeignKey(blank=True, help_text='Plan tarifaire associé au device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='billing.devicetariffplan'),
        ),
    ]
