# Generated by Django 6.0.1 on 2026-01-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicesettings_device_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='idling_speed_limit',
            field=models.IntegerField(default=3, help_text='Vitesse max considérée comme ralenti (km/h)'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='idling_threshold',
            field=models.IntegerField(default=5, help_text='Durée du moteur au ralenti avant alerte (minutes)'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='offline_timeout',
            field=models.IntegerField(default=10, help_text='Délai avant de considérer le device hors ligne (minutes)'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Fuseau horaire du device (ex: 'Africa/Douala')", max_length=50),
        ),
    ]
