# Generated by Django 6.0.1 on 2026-04-30 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_devicesettings_idling_speed_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code du protocole (ex: GT06, TK103) envoyé par l'ingestion", max_length=50, unique=True)),
                ('tcp_port', models.IntegerField(blank=True, help_text="Port TCP utilisé par l'ingestion", null=True)),
                ('udp_port', models.IntegerField(blank=True, help_text="Port UDP utilisé par l'ingestion", null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protocole',
                'verbose_name_plural': 'Protocoles',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='supported_features',
            field=models.JSONField(blank=True, default=list, help_text="Liste des fonctionnalités supportées (ex: ['engine_cut', 'sos_button'])"),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='protocol',
            field=models.ForeignKey(help_text='Protocole de communication (ex: GT06)', on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='devices.protocol'),
        ),
    ]
