# Generated by Django 6.0.1 on 2026-01-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('shape_type', models.CharField(choices=[('circle', 'Cercle'), ('polygon', 'Polygone'), ('rectangle', 'Rectangle')], max_length=20)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.FloatField(blank=True, null=True)),
                ('coordinates', models.JSONField(blank=True, default=list, help_text='Liste de coordonnées [[lat, lng], ...]')),
                ('color', models.CharField(default='#FF0000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='geofences', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Géofence',
                'verbose_name_plural': 'Géofences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GPSPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude en degrés décimaux')),
                ('longitude', models.FloatField(help_text='Longitude en degrés décimaux')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude en mètres', null=True)),
                ('speed', models.FloatField(default=0.0, help_text='Vitesse en km/h')),
                ('heading', models.FloatField(blank=True, help_text='Direction en degrés (0-360)', null=True)),
                ('satellites', models.IntegerField(blank=True, help_text='Nombre de satellites', null=True)),
                ('hdop', models.FloatField(blank=True, help_text='Horizontal Dilution of Precision', null=True)),
                ('ignition', models.BooleanField(blank=True, help_text='État du contact', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Niveau de batterie en pourcentage', null=True)),
                ('external_power', models.FloatField(blank=True, help_text='Tension alimentation externe en volts', null=True)),
                ('odometer', models.FloatField(blank=True, help_text='Kilométrage total en km', null=True)),
                ('fuel_level', models.FloatField(blank=True, help_text='Niveau de carburant en %', null=True)),
                ('temperature_1', models.FloatField(blank=True, null=True)),
                ('temperature_2', models.FloatField(blank=True, null=True)),
                ('io_data', models.JSONField(blank=True, default=dict, help_text='Données des entrées/sorties (portes, capteurs, etc.)')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp de la position GPS')),
                ('server_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp de réception par le serveur')),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_data', models.TextField(blank=True, help_text='Données brutes reçues', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Position traitée pour alertes et rapports')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='devices.device')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Entrée'), ('exit', 'Sortie')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='devices.device')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.geofence')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.gpsposition')),
            ],
            options={
                'verbose_name': 'Événement géofence',
                'verbose_name_plural': 'Événements géofence',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Rapport journalier'), ('weekly', 'Rapport hebdomadaire'), ('monthly', 'Rapport mensuel'), ('custom', 'Rapport personnalisé'), ('trip', 'Rapport de trajet'), ('fuel', 'Rapport de carburant'), ('speed', 'Rapport de vitesse'), ('stops', "Rapport d'arrêts")], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Données du rapport')),
                ('file_path', models.FileField(blank=True, help_text='Fichier PDF/Excel généré', null=True, upload_to='reports/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('devices', models.ManyToManyField(related_name='reports', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('start_address', models.TextField(blank=True, null=True)),
                ('end_address', models.TextField(blank=True, null=True)),
                ('distance_km', models.FloatField(default=0.0, help_text='Distance totale en km')),
                ('max_speed', models.FloatField(default=0.0, help_text='Vitesse maximale en km/h')),
                ('avg_speed', models.FloatField(default=0.0, help_text='Vitesse moyenne en km/h')),
                ('fuel_consumed', models.FloatField(blank=True, help_text='Consommation de carburant en litres', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Résumé incluant arrêts, vitesses, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='devices.device')),
                ('end_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_ended', to='tracking.gpsposition')),
                ('start_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_started', to='tracking.gpsposition')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('ignition_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='devices.device')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tracking.trip')),
            ],
            options={
                'verbose_name': 'Arrêt',
                'verbose_name_plural': 'Arrêts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['device', '-timestamp'], name='tracking_gp_device__09d285_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['device', 'timestamp'], name='tracking_gp_device__3e56c2_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['-server_time'], name='tracking_gp_server__b581f6_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsposition',
            index=models.Index(fields=['is_processed'], name='tracking_gp_is_proc_768ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['device', '-timestamp'], name='tracking_ge_device__cf8663_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['geofence', '-timestamp'], name='tracking_ge_geofenc_fadc86_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', '-created_at'], name='tracking_re_user_id_d35352_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='tracking_re_status_1a57c4_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['device', '-start_time'], name='tracking_tr_device__eeabac_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_completed'], name='tracking_tr_is_comp_430c84_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['device', '-start_time'], name='tracking_st_device__d65897_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['trip'], name='tracking_st_trip_id_94c871_idx'),
        ),
    ]
