# Generated by Django 6.0.1 on 2026-01-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsposition',
            name='signal_strength',
            field=models.IntegerField(blank=True, help_text='Force du signal GSM en pourcentage (0-100)', null=True),
        ),
    ]
