# Generated by Django 6.0.1 on 2026-04-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteLabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, help_text='Domaine personnalisé (ex: track.monentreprise.com)', max_length=255, null=True, unique=True)),
                ('platform_name', models.CharField(default='Navic', max_length=100)),
                ('primary_color', models.CharField(default='#00CC99', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='whitelabel/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='whitelabel/favicons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Marque Blanche',
                'verbose_name_plural': 'Configurations Marque Blanche',
            },
        ),
    ]
