# Generated by Django 6.0.1 on 2026-01-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Couleur en hexadécimal', max_length=7)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='fleet.devicegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe de devices',
                'verbose_name_plural': 'Groupes de devices',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, help_text="Numéro d'employé", max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_category', models.CharField(blank=True, help_text='Catégorie du permis (A, B, C, D, E)', max_length=10, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rfid_tag', models.CharField(blank=True, help_text='Tag RFID ou iButton du conducteur', max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='devices.device')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Assignation conducteur',
                'verbose_name_plural': 'Assignations conducteurs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FleetStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_devices', models.IntegerField(default=0)),
                ('active_devices', models.IntegerField(default=0)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('total_fuel_liters', models.FloatField(default=0.0)),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_engine_hours', models.FloatField(default=0.0)),
                ('total_idle_hours', models.FloatField(default=0.0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('device_data', models.JSONField(blank=True, default=dict, help_text='Statistiques détaillées par device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='fleet.devicegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique de flotte',
                'verbose_name_plural': 'Statistiques de flotte',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('lpg', 'GPL'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], max_length=20)),
                ('quantity_liters', models.FloatField(help_text='Quantité en litres')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Coût total', max_digits=10)),
                ('price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('odometer_reading', models.IntegerField(help_text='Kilométrage au moment du plein')),
                ('is_full_tank', models.BooleanField(default=True, help_text='Plein complet ou partiel')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='fuel_receipts/')),
                ('filled_at', models.DateTimeField(help_text='Date et heure du plein')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='devices.device')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='fleet.driver')),
            ],
            options={
                'verbose_name': 'Entrée carburant',
                'verbose_name_plural': 'Entrées carburant',
                'ordering': ['-filled_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Vidange'), ('filter_change', 'Changement filtres'), ('tire_change', 'Changement pneus'), ('brake_service', 'Révision freins'), ('battery_replacement', 'Remplacement batterie'), ('inspection', 'Contrôle technique'), ('repair', 'Réparation'), ('other', 'Autre')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('odometer_reading', models.IntegerField(help_text='Kilométrage au moment de la maintenance')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, help_text="Coût de la main d'œuvre", max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Coût des pièces', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Coût total', max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('service_provider', models.CharField(blank=True, help_text='Garage ou prestataire', max_length=255, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='maintenance_invoices/')),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_mileage', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='devices.device')),
            ],
            options={
                'verbose_name': 'Enregistrement de maintenance',
                'verbose_name_plural': 'Enregistrements de maintenance',
                'ordering': ['-service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['user', 'is_active'], name='fleet_drive_user_id_46f4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['rfid_tag'], name='fleet_drive_rfid_ta_d14a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['driver', '-start_time'], name='fleet_drive_driver__503b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['device', '-start_time'], name='fleet_drive_device__dcb0df_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetstatistics',
            index=models.Index(fields=['user', '-date'], name='fleet_fleet_user_id_1b24a8_idx'),
        ),
        migrations.AddIndex(
            model_name='fleetstatistics',
            index=models.Index(fields=['group', '-date'], name='fleet_fleet_group_i_ef5c8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fleetstatistics',
            unique_together={('user', 'group', 'date')},
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['device', '-filled_at'], name='fleet_fuele_device__8a484d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['device', '-service_date'], name='fleet_maint_device__4e1260_idx'),
        ),
    ]
