# Generated by Django 6.0.1 on 2026-01-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('speed', 'Excès de vitesse'), ('geofence_enter', 'Entrée dans zone'), ('geofence_exit', 'Sortie de zone'), ('ignition_on', 'Contact allumé'), ('ignition_off', 'Contact éteint'), ('low_battery', 'Batterie faible'), ('power_cut', 'Coupure alimentation'), ('tow', 'Remorquage détecté'), ('sos', 'Bouton SOS'), ('harsh_acceleration', 'Accélération brusque'), ('harsh_braking', 'Freinage brusque'), ('sharp_turn', 'Virage serré'), ('idle', 'Ralenti prolongé'), ('offline', 'Device hors ligne'), ('maintenance_due', 'Maintenance due'), ('fuel_drop', 'Baisse de carburant'), ('temperature', 'Alerte température'), ('custom', 'Personnalisée')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions de déclenchement (ex: {speed_threshold: 120})')),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_webhook', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('additional_emails', models.JSONField(blank=True, default=list, help_text="Liste d'emails supplémentaires à notifier")),
                ('additional_phones', models.JSONField(blank=True, default=list, help_text='Liste de numéros de téléphone à notifier par SMS')),
                ('is_active', models.BooleanField(default=True)),
                ('active_days', models.JSONField(blank=True, default=list, help_text='Jours actifs [0-6] où 0=Lundi')),
                ('active_hours_start', models.TimeField(blank=True, null=True)),
                ('active_hours_end', models.TimeField(blank=True, null=True)),
                ('cooldown_minutes', models.IntegerField(default=5, help_text='Délai minimum entre deux alertes du même type (minutes)')),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Règle d'alerte",
                'verbose_name_plural': "Règles d'alerte",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('time', 'Temporel'), ('mileage', 'Kilométrage'), ('both', 'Temporel et kilométrage')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Effectué'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='active', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_mileage', models.IntegerField(blank=True, help_text='Kilométrage de maintenance en km', null=True)),
                ('notify_days_before', models.IntegerField(default=7, help_text='Nombre de jours avant échéance pour notifier')),
                ('notify_km_before', models.IntegerField(default=500, help_text='Nombre de km avant échéance pour notifier')),
                ('last_notification', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_mileage', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rappel de maintenance',
                'verbose_name_plural': 'Rappels de maintenance',
                'ordering': ['due_date', 'due_mileage'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification push'), ('webhook', 'Webhook')], max_length=20)),
                ('recipient', models.CharField(help_text='Email, numéro de téléphone ou URL', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Journal de notification',
                'verbose_name_plural': 'Journaux de notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict, help_text="Données supplémentaires liées à l'alerte")),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('acknowledged', 'Acquittée'), ('resolved', 'Résolue'), ('ignored', 'Ignorée')], default='new', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
