# Generated by Django 6.0.1 on 2026-01-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('devices', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.gpsposition'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device spécifique ou null pour tous les devices', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='maintenancereminder',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='devices.device'),
        ),
        migrations.AddField(
            model_name='maintenancereminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='alerts.alert'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['user', 'is_active'], name='alerts_aler_user_id_90d438_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['device', 'is_active'], name='alerts_aler_device__6cf56e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status', '-triggered_at'], name='alerts_aler_user_id_607bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-triggered_at'], name='alerts_aler_device__b9616c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_aler_status_2a92cb_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereminder',
            index=models.Index(fields=['device', 'status'], name='alerts_main_device__b9840f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereminder',
            index=models.Index(fields=['due_date'], name='alerts_main_due_dat_6501ad_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['alert', '-created_at'], name='alerts_noti_alert_i_2126cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='alerts_noti_status_c78996_idx'),
        ),
    ]
